package com.game.planevadegame.questionandAnswer.wordlist;

import java.util.HashMap;

public class wordList {
    public static HashMap<String, String> questionsWithAnswers = new HashMap<>();

    public static void loadWordList() {

        questionsWithAnswers.put("in programming, what is the primary purpose of a variable?", "storage");
        questionsWithAnswers.put("can you explain the concept of a loop and its use in programming?", "repetition");
        questionsWithAnswers.put("what is an array and why is it used in programming?", "collection");
        questionsWithAnswers.put("what does a function represent in a program?", "subroutine");
        questionsWithAnswers.put("how does recursion work in programming?", "self-call");
        questionsWithAnswers.put("what is the significance of a class in object-oriented programming?", "blueprint");
        questionsWithAnswers.put("in oop, what does an object represent?", "instance");
        questionsWithAnswers.put("what does inheritance allow in object-oriented programming?", "reuse");
        questionsWithAnswers.put("can you explain polymorphism in the context of programming?", "flexibility");
        questionsWithAnswers.put("what is encapsulation and why is it important in programming?", "security");
        questionsWithAnswers.put("how does abstraction help in managing program complexity?", "simplification");
        questionsWithAnswers.put("what is an ide and how does it assist programmers?", "development");
        questionsWithAnswers.put("in programming, what role does a pointer play?", "reference");
        questionsWithAnswers.put("what is the main feature of a stack data structure?", "lifo");
        questionsWithAnswers.put("how does a queue operate in data handling?", "fifo");
        questionsWithAnswers.put("what is a list in programming, and what is its use?", "sequence");
        questionsWithAnswers.put("what is a dictionary, and how is it used in programming?", "mapping");
        questionsWithAnswers.put("how is a set different from other collections in programming?", "unique");
        questionsWithAnswers.put("what is the purpose of a module in programming?", "component");
        questionsWithAnswers.put("what is the function of a software library?", "reuse");
        questionsWithAnswers.put("how does a framework assist in software development?", "structure");
        questionsWithAnswers.put("what is a compiler's role in programming?", "translation");
        questionsWithAnswers.put("what does an interpreter do with source code?", "execution");
        questionsWithAnswers.put("what is a script in programming?", "automation");
        questionsWithAnswers.put("what is an api, and why is it important?", "interface");
        questionsWithAnswers.put("how is json utilized in web development?", "data format");
        questionsWithAnswers.put("what is xml primarily used for?", "markup");
        questionsWithAnswers.put("what role does html play in web development?", "structure");
        questionsWithAnswers.put("what is the purpose of css in web design?", "style");
        questionsWithAnswers.put("how is javascript used in web development?", "behavior");
        questionsWithAnswers.put("why is python favored in programming education?", "simplicity");
        questionsWithAnswers.put("what makes java a popular programming language?", "portability");
        questionsWithAnswers.put("what are the features of c++ in software development?", "performance");
        questionsWithAnswers.put("how is c# utilized in application development?", "versatility");
        questionsWithAnswers.put("what is php, and where is it commonly used?", "web development");
        questionsWithAnswers.put("what is sql used for in databases?", "query");
        questionsWithAnswers.put("how does nosql differ from traditional databases?", "flexibility");
        questionsWithAnswers.put("what is the purpose of a database query?", "retrieve");
        questionsWithAnswers.put("what is a transaction in a database system?", "operation");
        questionsWithAnswers.put("what operations are included in crud?", "create, read, update, delete");
        questionsWithAnswers.put("what is rest and its use in web services?", "architecture");
        questionsWithAnswers.put("how does soap function in web services?", "protocol");
        questionsWithAnswers.put("what is ajax and how is it used in web applications?", "asynchronous");
        questionsWithAnswers.put("what is a thread in the context of programming?", "task");
        questionsWithAnswers.put("what does concurrency allow in programming?", "simultaneity");
        questionsWithAnswers.put("what is the benefit of multithreading in applications?", "efficiency");
        questionsWithAnswers.put("what is a process in computing?", "execution");
        questionsWithAnswers.put("what is a daemon in the context of operating systems?", "background service");
        questionsWithAnswers.put("how does a socket facilitate network communication?", "endpoint");
        questionsWithAnswers.put("what is a port in networking?", "channel");
        questionsWithAnswers.put("what is the primary function of tcp?", "reliable connection");
        questionsWithAnswers.put("how does udp differ from tcp?", "unreliable");
        questionsWithAnswers.put("what is http used for on the internet?", "web communication");
        questionsWithAnswers.put("how does https enhance security over http?", "encryption");
        questionsWithAnswers.put("what is the role of ftp in network file transfers?", "file transfer");
        questionsWithAnswers.put("what is smtp used for?", "email transmission");
        questionsWithAnswers.put("how does ssh provide security in network communications?", "encryption");
        questionsWithAnswers.put("what is an ip address, and what does it identify?", "device");
        questionsWithAnswers.put("what is dns, and how does it work?", "name resolution");
        questionsWithAnswers.put("what is a url, and what does it represent?", "address");
        questionsWithAnswers.put("what is a domain in the context of the internet?", "address");
        questionsWithAnswers.put("how does a subdomain function under a main domain?", "prefix");
        questionsWithAnswers.put("what is caching, and how does it improve performance?", "storage");
        questionsWithAnswers.put("what is a cookie in web technology?", "data storage");
        questionsWithAnswers.put("what is a session in web applications?", "user interaction");
        questionsWithAnswers.put("how does authentication secure a system?", "verify identity");
        questionsWithAnswers.put("what is authorization in the context of security?", "access control");
        questionsWithAnswers.put("what is encryption used for in data security?", "protection");
        questionsWithAnswers.put("how does hashing ensure data integrity?", "checksum");
        questionsWithAnswers.put("what is binary in computing?", "base-2 numeral");
        questionsWithAnswers.put("what is an algorithm and its significance in programming?", "problem-solving");
        questionsWithAnswers.put("how does a data structure organize information?", "organization");
        questionsWithAnswers.put("what is a linked list, and how is it structured?", "nodes");
        questionsWithAnswers.put("what is a tree data structure used for?", "hierarchical data");
        questionsWithAnswers.put("how is a binary tree structured?", "two children");
        questionsWithAnswers.put("what is a binary search tree (bst)?", "sorted tree");
        questionsWithAnswers.put("how does a graph data structure represent relationships?", "nodes and edges");
        questionsWithAnswers.put("what is the purpose of dfs in graph traversal?", "depth-first");
        questionsWithAnswers.put("what is the purpose of bfs in graph traversal?", "breadth-first");
        questionsWithAnswers.put("what is a hashmap, and how does it store data?", "key-value pairs");
        questionsWithAnswers.put("what causes a stack overflow error?", "exceeding stack size");
        questionsWithAnswers.put("what is a buffer in computing?", "temporary storage");
        questionsWithAnswers.put("how does a buffer overflow occur?", "exceeding buffer size");
        questionsWithAnswers.put("what is the role of garbage collection in programming?", "memory management");
        questionsWithAnswers.put("what is a memory leak, and how does it affect a program?", "unused memory");
        questionsWithAnswers.put("what is a segmentation fault in computing?", "invalid memory access");
        questionsWithAnswers.put("what is an exception in programming?", "runtime error");
        questionsWithAnswers.put("what is the purpose of debugging in software development?", "fix errors");
        questionsWithAnswers.put("what is a breakpoint used for in debugging?", "pause execution");
        questionsWithAnswers.put("how does version control help in software development?", "track changes");
        questionsWithAnswers.put("what is git, and how is it used in version control?", "version control system");
        questionsWithAnswers.put("what is a repository in git?", "project storage");
        questionsWithAnswers.put("how does branching work in git?", "create new paths");
        questionsWithAnswers.put("what is the purpose of a merge in git?", "combine branches");
        questionsWithAnswers.put("what is a commit in version control?", "save changes");
        questionsWithAnswers.put("what is a pull request in git?", "propose changes");
        questionsWithAnswers.put("what is continuous integration in software development?", "automated testing");
        questionsWithAnswers.put("what is a build process in software development?", "compile code");
        questionsWithAnswers.put("what is deployment in the context of software?", "release software");
        questionsWithAnswers.put("what is devops, and how does it benefit software development?", "collaboration");

    }
}
